server:
  servlet:
    context-path: /api/cinema-app
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
app:
  application-id: ${X_APPLICATION_ID}
  connect-timeout: ${EXTERNAL_CONNECT_TIMEOUT}
  read-timeout: ${EXTERNAL_REQUEST_TIMEOUT}
  host: ${INTERNAL_BASE_URL}/api/cinema-app
  external-host: ${EXTERNAL_BASE_URL}/api/cinema-app
  max-processes-thread-executing: 1
  max-items-thread-executing: 1
  imdb:
    api-key: ${API_KEY_VALUE}
    get-movie-detail-url: "http://www.omdbapi.com/?apikey=:apiKey&i=:imdbId"

