server:
  servlet:
    context-path: /api/cinema-app
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    platform: postgresql
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
  jackson:
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
app:
  application-id: ${X_APPLICATION_ID}
  connect-timeout: ${EXTERNAL_CONNECT_TIMEOUT}
  read-timeout: ${EXTERNAL_REQUEST_TIMEOUT}
  host: ${INTERNAL_BASE_URL}/api/cinema-app
  external-host: ${EXTERNAL_BASE_URL}/api/cinema-app
  max-processes-thread-executing: 1
  max-items-thread-executing: 1
  zoho:
    api-key: ${API_KEY_VALUE}
    base-urls: '{
        "co": "${INTERNAL_CO}/api/zoho-middleware/v1",
        "mx": "${INTERNAL_MX}/api/zoho-middleware/v1",
        "br": "${INTERNAL_BR}/api/zoho-middleware/v1",
        "ar": "${INTERNAL_AR}/api/zoho-middleware/v1",
        "pe": "${INTERNAL_PE}/api/zoho-middleware/v1",
        "cl": "${INTERNAL_CL}/api/zoho-middleware/v1",
        "uy": "${INTERNAL_UY}/api/zoho-middleware/v1",
        "ec": "${INTERNAL_EC}/api/zoho-middleware/v1",
        "cr": "${INTERNAL_CR}/api/zoho-middleware/v1",
        "bo": "${INTERNAL_BO}/api/zoho-middleware/v1"
     }'
    external-base-urls: '{
        "co": "${EXTERNAL_CO}/api/zoho-middleware/v1",
        "mx": "${EXTERNAL_MX}/api/zoho-middleware/v1",
        "br": "${EXTERNAL_BR}/api/zoho-middleware/v1",
        "ar": "${EXTERNAL_AR}/api/zoho-middleware/v1",
        "pe": "${EXTERNAL_PE}/api/zoho-middleware/v1",
        "cl": "${EXTERNAL_CL}/api/zoho-middleware/v1",
        "uy": "${EXTERNAL_UY}/api/zoho-middleware/v1",
        "ec": "${EXTERNAL_EC}/api/zoho-middleware/v1",
        "cr": "${EXTERNAL_CR}/api/zoho-middleware/v1",
        "bo": "${EXTERNAL_BO}/api/zoho-middleware/v1"
    }'
    send-contact-url: /contact-store/to-zoho
    save-contact-validation-url: /contact-store/save-contact-validation
    cinema-app-download-result: /cinema-app/download-result

  communications:
    base-urls: '{
        "co": "${INTERNAL_CO}/api/communications-ms/internal-ms",
        "mx": "${INTERNAL_MX}/api/communications-ms/internal-ms",
        "br": "${INTERNAL_BR}/api/communications-ms/internal-ms",
        "ar": "${INTERNAL_AR}/api/communications-ms/internal-ms",
        "pe": "${INTERNAL_PE}/api/communications-ms/internal-ms",
        "cl": "${INTERNAL_CL}/api/communications-ms/internal-ms",
        "uy": "${INTERNAL_UY}/api/communications-ms/internal-ms",
        "ec": "${INTERNAL_EC}/api/communications-ms/internal-ms",
        "cr": "${INTERNAL_CR}/api/communications-ms/internal-ms",
        "bo": "${INTERNAL_BO}/api/communications-ms/internal-ms"
     }'
    validate-whatsapp-url: /whatsapp/validate-numbers
    interactive-call-url: /interactive-call

  messagebird:
    base-urls: '{
            "co": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID}/invoke",
            "br": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_BR}/invoke",
            "mx": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_MX}/invoke",
            "ar": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_AR}/invoke",
            "pe": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_PE}/invoke",
            "cl": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_CL}/invoke",
            "uy": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_UY}/invoke",
            "ec": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_EC}/invoke",
            "cr": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_CR}/invoke",
            "bo": "${MESSAGEBIRD_FLOWS_URL}/flows/${MESSAGEBIRD_VALIDATION_FLOW_ID_BO}/invoke"
        }'

  rs-onboarding-support:
    base-urls: '{
          "co": "${INTERNAL_CO}/api/rs-onboarding-support",
          "mx": "${INTERNAL_MX}/api/rs-onboarding-support",
          "br": "${INTERNAL_BR}/api/rs-onboarding-support",
          "ar": "${INTERNAL_AR}/api/rs-onboarding-support",
          "pe": "${INTERNAL_PE}/api/rs-onboarding-support",
          "cl": "${INTERNAL_CL}/api/rs-onboarding-support",
          "uy": "${INTERNAL_UY}/api/rs-onboarding-support",
          "ec": "${INTERNAL_EC}/api/rs-onboarding-support",
          "cr": "${INTERNAL_CR}/api/rs-onboarding-support",
          "bo": "${INTERNAL_BO}/api/rs-onboarding-support"
        }'
    update-contact-store-url: /store/#storeId
  rs-store-statistics:
    base-urls: '{
              "co": "${INTERNAL_CO}/api/rs-store-statistics",
              "mx": "${INTERNAL_MX}/api/rs-store-statistics",
              "br": "${INTERNAL_BR}/api/rs-store-statistics",
              "ar": "${INTERNAL_AR}/api/rs-store-statistics",
              "pe": "${INTERNAL_PE}/api/rs-store-statistics",
              "cl": "${INTERNAL_CL}/api/rs-store-statistics",
              "uy": "${INTERNAL_UY}/api/rs-store-statistics",
              "ec": "${INTERNAL_EC}/api/rs-store-statistics",
              "cr": "${INTERNAL_CR}/api/rs-store-statistics",
              "bo": "${INTERNAL_BO}/api/rs-store-statistics"
            }'
    email-verification-url: /files/emails_zoho_communication.csv

  amazon:
    region: ${AWS_REGION}
    bucket: ${S3_BUCKET}
    access-key: ${AWS_SECRET_KEY}
    secret-key: ${AWS_SECRET_ACCESS_KEY}